on: 
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: string     
name: External Push
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ajit there."